name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.USERNAME }}
          docker_compose_prefix: example_com

#      - name: Install SSH
#        run: sudo apt-get install openssh-client
#      - name: Deploy to VPS
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd tests/deploytest/
#            docker-compose pull
#            docker-compose up -d


