name: Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to VPS
      - uses: appleboy/ssh-action@master
        with:
          host: 45.137.66.185
          username: ${{ secrets.EXAMPLE_COM_SSH_USER }}
          key: ${{ secrets.EXAMPLE_COM_SSH_PRIVATE_KEY }}
          script: |
            cd tests/deploytest/
            docker-compose pull
            docker-compose up -d
